org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

mod_id=reinhardtshbm
mod_group=com.reinhardt.hbm
mod_version=0.1.0-alpha

mod_name=Reinhardt's HBM
mod_description=Early NeoForge 1.21.1 porting workspace for HBM's Nuclear Tech Mod.
mod_license=GPL-3.0-or-later, LGPL-3.0-or-later
mod_authors=Reinhardt, HbmMods
local_client_mods_dir=E:/MC/1.21.1/.minecraft/versions/1.21.1-NeoForge_21.1.248/mods

loader_version_range=[3,)
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]

neo_version=21.1.248
neo_version_range=[21.1.248,)

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
